"""
Self-contained HTML report for a screening run.

Renders results.json (plus optional evaluation text) into a single
report.html with the annotated images embedded as base64 — openable in any
browser on an air-gapped machine, no server and no external assets.

Importable:
    from trojanlib import write_report
    path = write_report(out_dir, eval_text="")
"""
from __future__ import annotations

import base64
import html
import io
import json
from pathlib import Path


def _thumb(path: Path, width=560) -> str:
    """Inline <img> as base64 (downscaled thumbnail keeps the report small)."""
    try:
        from PIL import Image
        import io
        im = Image.open(path)
        if im.width > width:
            im = im.resize((width, int(im.height * width / im.width)))
        buf = io.BytesIO()
        im.save(buf, "PNG")
        data = buf.getvalue()
    except Exception:
        data = path.read_bytes()
    return ("<img src='data:image/png;base64,"
            + base64.b64encode(data).decode() + "' style='max-width:100%'>")


def write_report(out_dir: Path, eval_text: str = "",
                 summary_text: str = "") -> Path:
    report = json.loads((out_dir / "results.json").read_text())
    s = report["summary"]
    ann = out_dir / "annotated"
    cat = {c["pattern"]: c for c in report["catalog"]}

    rows = []
    for name, rec in sorted(report["images"].items(),
                            key=lambda kv: -kv[1]["count"]):
        flagged = rec["status"] == "trojan_detected"
        dets = "".join(
            f"<li><b>{d['pattern']}</b> — {html.escape(d['name'])} "
            f"<i>({html.escape(d['class'])})</i>, bbox {d['bbox']}, "
            f"conf {d['confidence']:.0%}</li>" for d in rec["detections"])
        img_html = ""
        if flagged and (ann / name).exists():
            img_html = _thumb(ann / name)
        badge = ("<span class='bad'>TROJAN DETECTED</span>" if flagged
                 else "<span class='ok'>no trojan detected</span>")
        rows.append(
            f"<div class='card'><h3>{html.escape(name)} {badge}</h3>"
            + (f"<ul>{dets}</ul>" if dets else "")
            + img_html + "</div>")

    per = "".join(
        f"<tr><td><b>{k}</b></td><td>{html.escape(cat[k]['name'])}</td>"
        f"<td>{html.escape(cat[k]['class'])}</td>"
        f"<td style='text-align:right'>{v}</td></tr>"
        for k, v in report["summary"]["per_pattern"].items())

    ev = (f"<h2>Evaluation vs ground truth</h2><pre>{html.escape(eval_text)}"
          "</pre>" if eval_text else "")
    # Optional analyst narrative from Claude (via Open WebUI). Rendered as
    # paragraphs/bullets, escaped — it is model output, never trusted markup.
    if summary_text:
        blocks = []
        for para in summary_text.split("\n\n"):
            lines = [ln.strip() for ln in para.strip().splitlines() if ln.strip()]
            if lines and all(ln[:2] in ("- ", "* ") or ln[:1].isdigit()
                             for ln in lines):
                items = "".join(f"<li>{html.escape(ln.lstrip('-*0123456789. '))}"
                                "</li>" for ln in lines)
                blocks.append(f"<ul>{items}</ul>")
            elif lines:
                blocks.append("<p>" + html.escape(" ".join(lines)) + "</p>")
        sm = ("<h2>Analyst summary</h2><div class='summary'>"
              + "".join(blocks)
              + "<p class='muted'>Generated by a Claude model via Open WebUI "
                "from the detector's findings. Potential trojans requiring "
                "human review.</p></div>")
    else:
        sm = ""

    page = f"""<!doctype html><html><head><meta charset='utf-8'>
<title>Trojan screening report</title><style>
 body{{font-family:system-ui,sans-serif;margin:24px auto;max-width:900px;
      background:#111;color:#ddd}}
 h1,h2,h3{{color:#fff}} .ok{{color:#3fbf6f}} .bad{{color:#ff5252;font-weight:700}}
 table{{border-collapse:collapse}} td,th{{border:1px solid #444;padding:4px 10px}}
 .card{{border:1px solid #333;border-radius:8px;padding:12px 16px;margin:14px 0;
       background:#181818}}
 pre{{background:#181818;padding:10px;overflow-x:auto}}
 .summary{{border-left:3px solid #3fbf6f;padding:2px 16px;background:#161d18;
          border-radius:0 8px 8px 0}}
 .muted{{color:#888;font-size:.9em}}
</style></head><body>
<h1>Trojan screening report</h1>
<p>generated {html.escape(report['generated'])} · backend
 <b>{html.escape(report['backend'])}</b></p>
<p><b>{s['images']}</b> images screened —
 <span class='bad'>{s['flagged']} flagged</span>,
 <span class='ok'>{s['clean']} clean</span>,
 {s['detections']} detections total.</p>
<h2>Detections per pattern</h2>
<table><tr><th>key</th><th>name</th><th>class</th><th>count</th></tr>{per}</table>
{sm}
{ev}
<h2>Per-image results</h2>
{''.join(rows)}
</body></html>"""
    p = out_dir / "report.html"
    p.write_text(page)
    return p
